In [2]:
import duckdb
from pathlib import Path
import pandas as pd

# 네이버 데이터 DB로 옮기기

In [3]:
# 네이버 데이터 파일 위치
datafiles_dir = Path("G:/My Drive/Data/naver_search_results")
restaurants_path = datafiles_dir / "restaurants_table.parquet"
navermap_reviews_path = datafiles_dir / "navermap_reviews.parquet"
naverblog_reviews_path = datafiles_dir / "naverblog_reviews_store_id.parquet" # store_id 추가 버전
navermap_reviews_labelled_path = datafiles_dir / "navermap_reviews_labelled.parquet" # 라벨링을 위해 샘플링한 애들만 모아둔 파일. 완전한 라벨링은 안 된 상태 but 라벨링 된 애들만 가지고 모델 훈련 중...

In [4]:
# 새로운 DB 파일 위치 (G 드라이브, H 드라이브 등 어디에 있는 지 확인해주세요)
new_db_path = Path(r"H:\My Drive") / "reviews.db"

In [ ]:
with duckdb.connect(database=new_db_path, read_only=False) as db_conn:
    q1 = f"CREATE OR REPLACE TABLE naver_restaurants AS SELECT * FROM '{restaurants_path.as_posix()}'"
    db_conn.execute(q1)
    q2 = f"CREATE OR REPLACE TABLE navermap_reviews AS SELECT * FROM '{navermap_reviews_path.as_posix()}'"
    db_conn.execute(q2)
    q3 = f"CREATE OR REPLACE TABLE naverblog_reviews AS SELECT * FROM '{naverblog_reviews_path.as_posix()}'"
    db_conn.execute(q3)
    q4 = f"CREATE OR REPLACE TABLE navermap_reviews_labelled AS SELECT * FROM '{navermap_reviews_labelled_path.as_posix()}'"
    db_conn.execute(q4)

In [ ]:
local_db_path = Path(r"C:\Users\m\2025\project\code_only\real_matjib_code\reviews_local.db")
with duckdb.connect(database=local_db_path, read_only=False) as db_conn:
    q1 = f"CREATE OR REPLACE TABLE naver_restaurants AS SELECT * FROM '{restaurants_path.as_posix()}'"
    db_conn.execute(q1)
    q2 = f"CREATE OR REPLACE TABLE navermap_reviews AS SELECT * FROM '{navermap_reviews_path.as_posix()}'"
    db_conn.execute(q2)
    q3 = f"CREATE OR REPLACE TABLE naverblog_reviews AS SELECT * FROM '{naverblog_reviews_path.as_posix()}'"
    db_conn.execute(q3)

In [14]:
local_db_path = Path(r"C:\Users\m\2025\project\code_only\real_matjib_code\reviews_local.db")
with duckdb.connect(database=local_db_path) as conn:
    df = conn.table("navermap_reviews").fetchdf()
    display(df.T)

,0,1,2,3,4,5,6,7,8,9,...,293592,293593,293594,293595,293596,293597,293598,293599,293600,293601
review_id,6828df8fb0df3c4081c31b51,6826330c4ac4114f974f8e2e,6828ea26e020e7520abbef29,6828d369ba6d7b7c9d7b3cab,6829f068abbd149b84e655e4,6828933892365eaf5831cf31,682b30905943d86b8318fdbc,68262db5227d3640fb09b669,682a91ffd18f04a3581c6416,682926a2c724fdea0112f11c,...,5e849adbf483b900128b3739,5ecafe13d10a530011a1b211,5eea9a3c97208500105f7f32,5f185aa5c973e70010399cf8,5f13eb2391480900106f83e4,5e548a92dc00d40011cb040b,5e548a5521943f0011d37227,5eb96e4da437330010937e6a,5e60b0802c4d1600113c118e,5e54ed074309c300112bbfad
store_id,2038175452,2038175452,2038175452,2038175452,2038175452,2038175452,2038175452,2038175452,2038175452,2038175452,...,31036949,31036949,31036949,31036949,31036949,31036949,31036949,31036949,31036949,31036949
store_naver_name,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,...,코리아식당,코리아식당,코리아식당,코리아식당,코리아식당,코리아식당,코리아식당,코리아식당,코리아식당,코리아식당
store_name,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,서울혼술바 제주아홉 홍대점,...,코리아,코리아,코리아,코리아,코리아,코리아,코리아,코리아,코리아,코리아
store_reply,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
review_text,최근간 혼술바 중에 진짜 베스트였어요\n술 종류도 다양했고 술찌인 저도 먹을 수 있...,혼자 왔는데 사장님 분들이 다 친절하셔서 마감까지 재밌게 놀고 가요~! 시그니처 칵...,난생 처음가본 혼술바 홍대는 항상 친구들 이랑만 놀러 가는 장소였는데 이렇게 편하고...,사람들이랑 소소한 대화 나누기도 좋고\n칵테일도 맛있어요🫶🏻,제주도에서도 가봤는데 너무 좋아서 홍대점도 가보니 역시나 좋네요ㅠ !! \n혼술바 ...,가오픈에 미리 와봤는데 혼자 와도 친구랑 와도 편하게 어울릴 수 있는 분위기인 혼술...,혼술하러 왔다가 친구 사귀고 가요\n너무 재밌어요!,"서귀포에서 방문했던 기억이 너무 좋아서, 이번에 홍대에 오픈했다길래 방문했습니다! ...",첫번째 방문이 되게 좋은 기억이었어서 재방문 했습니다! 가볍게 술 한 잔 하고 대화...,"사장님 너무 친절하시고 분위기,인테리어도 취향이라 기분좋게 마셨습니다!☺️\n또 방...",...,#연남동 #괜찮음 #약간비싼편,집밥 먹고싶을때 가는곳,맛있어요,맛나요,맛남,이 맛에 이 가격 어쩔겁니까!\n집근처면 매일 가고싶네요*ㅁ*,코리아식당 상호명이랑 딱맞아요 한국대표 가정식임,비지찌게 최애메뉴,곱창전골 굿,진정한 맛집!!
num_of_media,10,3,1,1,1,0,1,0,0,0,...,1,0,1,0,0,0,0,0,0,0
image_links,[https://pup-review-phinf.pstatic.net/MjAyNTA1...,[https://pup-review-phinf.pstatic.net/MjAyNTA1...,[https://pup-review-phinf.pstatic.net/MjAyNTA1...,[https://pup-review-phinf.pstatic.net/MjAyNTA1...,[https://pup-review-phinf.pstatic.net/MjAyNTA1...,<NA>,[https://pup-review-phinf.pstatic.net/MjAyNTA1...,<NA>,<NA>,<NA>,...,[https://pup-review-phinf.pstatic.net/MjAyMzEw...,<NA>,[https://pup-review-phinf.pstatic.net/MjAyMzEw...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
video_thumbnail_links,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
visit_count,1,1,1,1,1,1,1,1,2,1,...,1,1,1,2,1,1,1,1,1,1
author_nickname,미농쓰S2,mnz****,choisg1219,김 융,우채연96,스파이더맨할래토르할래,dol****,rla63446,rla63446,비람70,...,망유랑,tnd****,다빔잉,mel****,mel****,옴쓰,져니비손스,포차코키티흰둥이,명교80,테스터기
author_total_reviews,9.0,18.0,4.0,26.0,14.0,13.0,11.0,21.0,21.0,16.0,...,579.0,415.0,318.0,211.0,211.0,473.0,117.0,419.0,174.0,241.0
author_total_images,26.0,24.0,5.0,51.0,3.0,22.0,5.0,4.0,4.0,3.0,...,360.0,79.0,200.0,16.0,16.0,9.0,32.0,7.0,3.0,4.0
reactions_fun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
reactions_helpful,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
reactions_wannago,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
reactions_cool,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
review_datetime,2025-05-17 19:04:53,2025-05-15 18:26:42,2025-05-16 15:27:39,2025-05-17 16:36:59,2025-05-18 14:14:54,2025-05-16 15:27:39,2025-05-19 13:19:49,2025-05-15 14:27:35,2025-05-17 14:03:47,2025-05-17 17:48:45,...,2020-04-01 10:18:00,2020-05-23 08:46:00,2020-06-16 09:09:00,2020-07-22 06:43:00,2020-07-18 09:12:00,2020-02-25 02:33:00,2020-02-25 02:33:00,2020-02-28 12:22:00,2020-03-05 07:55:00,2020-02-25 02:33:00
review_year,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025,...,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
visit_keywords,"[예약 없이 이용, 바로 입장, 친목, 친구]","[예약 없이 이용, 바로 입장, 일상, 혼자]","[예약 없이 이용, 바로 입장, 혼자]","[예약 없이 이용, 바로 입장, 친목, 친구]","[예약 없이 이용, 바로 입장, 친목, 친구]","[예약 없이 이용, 바로 입장, 일상, 친구]","[예약 없이 이용, 바로 입장, 친목, 친구]","[예약 없이 이용, 바로 입장, 나들이, 혼자]","[예약 없이 이용, 바로 입장, 나들이, 혼자]","[예약 없이 이용, 바로 입장, 친목, 친구]",...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
purchase_item,파우스트,블랙아홉,말리부 하이볼,얼그레이 하이볼,피치 하이볼,말리부 하이볼,갓파더,얼그레이 하이볼,얼그레이 하이볼,제주모히또,...,가자미구이,None,None,None,None,None,None,None,None,None
rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,5.0,5.0,5.0,5.0,5.0,5.0,4.5,5.0,5.0
keyword_tags_code,"[alcohol_var, drink_good, talk_good, atmospher...","[talk_good, food_good, alcohol_var, special_me...","[alcohol_var, interior_cool, music_good, talk_...","[interior_cool, talk_good, drink_alone, alcoho...","[interior_cool, talk_good, drink_alone, snack_...","[interior_cool, drink_alone, spacious, alcohol...","[food_good, alcohol_var, special_menu, interio...","[alcohol_var, interior_cool, music_good, talk_...","[alcohol_var, special_menu, music_good, talk_g...","[food_good, interior_cool, kind]",...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
keyword_tags_hangul,"[술이 다양해요, 음료가 맛있어요, 대화하기 좋아요, 차분한 분위기에요, 컨셉이 독...","[대화하기 좋아요, 음식이 맛있어요, 술이 다양해요, 특별한 메뉴가 있어요, 친절해요]","[술이 다양해요, 인테리어가 멋져요, 음악이 좋아요, 대화하기 좋아요, 친절해요]","[인테리어가 멋져요, 대화하기 좋아요, 혼술하기 좋아요, 술이 다양해요, 특별한 메...","[인테리어가 멋져요, 대화하기 좋아요, 혼술하기 좋아요, 기본 안주가 좋아요, 술이...","[인테리어가 멋져요, 혼술하기 좋아요, 매장이 넓어요, 술이 다양해요, 특별한 메뉴...","[음식이 맛있어요, 술이 다양해요, 특별한 메뉴가 있어요, 인테리어가 멋져요, 혼술...","[술이 다양해요, 인테리어가 멋져요, 음악이 좋아요, 대화하기 좋아요, 혼술하기 좋아요]","[술이 다양해요, 특별한 메뉴가 있어요, 음악이 좋아요, 대화하기 좋아요, 혼술하기...","[음식이 맛있어요, 인테리어가 멋져요, 친절해요]",...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
__index_level_0__,0,1,2,3,4,5,6,7,8,9,...,293593,293594,293595,293596,293597,293598,293599,293600,293601,293602

# DB에서 정보 보기

In [ ]:
with duckdb.connect(database=new_db_path, read_only=False) as db_conn:
    # DB에 어떤 테이블 있는 지 보기
    db_conn.sql("PRAGMA show_tables_expanded;").show() 
    # 데이터프레임으로 테이블 가져오기
    restaurants = db_conn.table("restaurants").to_df() 
    display(restaurants)

In [ ]:
with duckdb.connect(database=new_db_path, read_only=True) as db_conn:
    navermap = db_conn.table("navermap_reviews").to_df() 
    display(navermap.T)

,0,1,2,3,4,5,6,7,8,9,...,293592,293593,293594,293595,293596,293597,293598,293599,293600,293601
review_id,65f6d3fd9eedd93dec6a0738,6683d5ba670ce9972df62a80,6636183d3bf46185f1dabf13,65a11316c1be5c5de56162e7,6685fd18a40e9b88f1e12939,65ed6b99c9d09afe4d31680d,65eee52fb03e3a29896a339b,65f576c0234a6f943c1ddbd4,65e2f33f9ab21d7ec49d6db9,65f565052120d04b92e51bc1,...,65cb543750061758bf95c425,65d74c6529860ea1919b8dae,65d8718951b6f65046ab6416,659bbf0452dca0127701a962,659e6f9607f10216c2de74be,6654600ea2bb7356e00eaa4e,664e00d255673be2b7ae05c4,661293eb52c90e6b49f28ea7,65a8ea19e0d26b49e31335cd,655d430114a377991d84f33b
review_text,사와를 너무 좋아해서 일부러 찾아왔어요!! 이런 일본풍 술집 러버로써 정말 강추드립...,마싯어요,안주도 맛있고 시원하고 사장님도 친절하세요~! \n연남동 오면 꼭 들리시는걸 추천합...,직원분들도 너무 친절하시구 금요일이라 예약하고 갔는데 바로 입장해서 너무좋았당!!\...,,오랜만에 친한 언니와 하타네 왔어요푸ㅠ 하이볼 넘 맛있음..!! 하이볼 좋아하시고 ...,너무너무 와보고 싶었어요…\n오자마자 바로 주문하고 먹을려는데\n친절히 메뉴마다 설...,처음 와봤는데 분위기 맛집에 사람도 적당해서 너무 좋아요!!,메뉴도 전부 맛있었고 사케도 다 맛있어요 🥺 다음에 재방문 의사 200%입니다!,분위기도 좋고 안주도 맛있어요 😆 \n다음에 또 올게요 🎉\n,...,오픈 초반에 아지트처럼 자주 방문했었는데 어느 순간 웨이팅이 생기면서 오랜만에 방문...,우리 아지트 빼애애앰 항상 맛있게 먹고 가요 타코야끼 오꼬노미야끼 야끼소바 하이볼 ...,메뉴마다 다 맛있고 맥주 안주로 딱 좋아요. 손님이 계속 들어오는 맛집입니다. 일본...,일식 좋아하는 사람으로써 미친맛도리 감성 맛집을 찾았어요ㅠㅠ 맥주 한잔 마시고 싶을...,집 앞이었으면 매주 왔을 것 같아요!!!\n모두 친절하고 음식도 너무 맛있어요! \...,타코야끼도 바삭하고 야끼소바에 마라맛이 많이 나서 좋았어요!!,타코야끼 맛집~,시오소바 맛있어요! 타코야끼도 양많고 바삭해요~,진짜 여기만 오면 폭식해요!!!!!너무 맛있습니다 그리고 너무 친절하세요 다음에 또...,연남동 타코야끼 맛집이네요👍🏻\n포장해가는 사람도 많고 매장도 분위기가 넘 좋아요\...
store_id,1831606473,1831606473,1831606473,1831606473,1831606473,1831606473,1831606473,1831606473,1831606473,1831606473,...,1931292312,1931292312,1931292312,1931292312,1931292312,1931292312,1931292312,1931292312,1931292312,1931292312
store_naver_name,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,하타네 연남점,...,열정타코,열정타코,열정타코,열정타코,열정타코,열정타코,열정타코,열정타코,열정타코,열정타코
category,[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],[['술집' '이자카야']],...,[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']],[['술집' '요리주점']]
image_links,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[],[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[],[],[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyND...,[['https://pup-review-phinf.pstatic.net/MjAyMz...
video_thumbnail_links,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],[]
store_reply,행복070님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 정말 다행...,None,ddugh님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 다행입니다...,None,None,나샷94님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 다행입니다~...,주희15님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 다행입니다~...,권민성4789님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 정말 ...,이웃집또털어520님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 다...,징둥둥님 소중한 리뷰 감사합니다 ㅎㅎㅎㅎ 💛 음식이 입맛에 맞으셨다니 정말 다행입니...,...,None,None,None,추운 날씨에도 방문 해주셨는데 소중한 리뷰도 정말 감사드립니다 ! 새해 복 많이 받...,"요즘 감자샐러드와 타코야끼, 여기에 생맥주까지 드시는 분들이 많더라구요 ! 맛있게 ...",안녕하세요 열정타코 입니다 ~! \n요즘 많은 분들이 찾는 메뉴 마라 야끼소바!!\...,타코야키 맛집 !! 열정타코 \n소중한 리뷰 정말 감사드려요!,시오야끼소바 괜찮으셨나욥??!! 오홋 \n소중한 리뷰 정말 감사드리고\n항상 노력하...,"우와... 역시 타코야끼와 야끼소바의 환상적인 조합,,, 이걸 어떻게 참을 수 있나...",소중한 시간에 리뷰 정말 감사드려욥!!!\n날씨도 추운데 방문해주셔서 또 감사드립니...
num_of_media,1,1,0,2,1,1,1,1,3,1,...,2,3,3,1,4,0,0,1,3,3
visit_count,1,1,1,1,1,2,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
author_total_reviews,9.0,13.0,10.0,59.0,5.0,15.0,11.0,36.0,13.0,148.0,...,14.0,15.0,5.0,1813.0,48.0,6.0,1381.0,26.0,92.0,53.0
author_total_images,18.0,15.0,1.0,66.0,4.0,17.0,10.0,30.0,15.0,29.0,...,3.0,23.0,7.0,2074.0,60.0,3.0,76.0,47.0,24.0,90.0
reactions_fun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
reactions_helpful,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
reactions_wannago,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
reactions_cool,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
review_year,2024,2024,2024,2024,2024,2024,2024,2024,2024,2024,...,2024,2024,2024,2024,2024,2024,2024,2024,2024,2023
rating,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
review_datetime,2024-03-17T11:22:00.000000,2024-07-01T13:03:36.000000,2024-05-04T11:12:00.000000,2024-01-11T10:20:31.000000,2024-07-03T10:00:00.000000,2024-03-10T08:10:03.000000,2024-03-10T14:54:49.000000,2024-03-16T10:26:30.000000,2024-03-02T09:35:00.000000,2024-03-15T15:02:00.000000,...,2024-02-12T23:31:11.000000,2024-02-22T13:27:00.000000,2024-02-23T09:20:00.000000,2024-01-08T09:20:00.000000,2024-01-10T10:19:00.000000,2024-05-26T22:25:10.000000,2024-05-17T00:45:35.000000,2024-04-07T00:08:53.000000,2024-01-18T09:03:00.000000,2023-11-20T11:09:00.000000
visit_keywords,[['예약 없이 이용' '바로 입장' '데이트' '친목' '친구']],[['예약 없이 이용' '바로 입장' '친목' '친구']],[['10분 이내 ' '회식' '친구']],[['예약 후 이용' '바로 입장' '데이트' '나들이' '연인・배우자']],[['예약 후 이용' '바로 입장' '친목' '지인・동료']],[['예약 없이 이용' '바로 입장' '친목' '친구']],[['예약 후 이용' '바로 입장' '친목' '회식' '친구' '지인・동료']],[['예약 없이 이용' '30분 이내' '데이트' '연인・배우자']],[['예약 없이 이용' '바로 입장' '친목' '친구']],[['예약 없이 이용' '바로 입장' '친목' '친구']],...,[['예약 없이 이용' '바로 입장' '데이트' '연인・배우자']],[['예약 없이 이용' '10분 이내 ' '데이트' '나들이' '연인・배우자']],[['예약 없이 이용' '바로 입장' '데이트' '연인・배우자']],[['예약 후 이용' '바로 입장' '일상' '친척・형제']],[['예약 없이 이용' '바로 입장' '데이트' '연인・배우자']],[['예약 없이 이용' '바로 입장' '데이트' '친구']],[['예약 없이 이용' '30분 이상' '일상' '지인・동료']],[['예약 없이 이용' '바로 입장' '데이트' '연인・배우자']],[['예약 없이 이용' '바로 입장' '친목' '친구']],[]
purchase_item,야키소바 1,하몽&멜론,크빠새 (모닝방),얼그레이 하이블,일반예약,핫 타코야키 (블케이노),바사삭닭껍질,하타네 하이불,하타네라면 (콩가루),(*)때려만든 오이무침 (리뷰서비스),...,14알,유자 하이볼(탄산),오꼬노미야끼,14알,14알,14알,생맥주,28일,14알,14알
keyword_tags_hangul,[['음식이 맛있어요' '특별한 메뉴가 있어요' '술이 다양해요' '음악이 좋아요'...,[['음식이 맛있어요' '기본 안주가 좋아요' '술이 다양해요' '매장이 청결해요']],[['음식이 맛있어요' '기본 안주가 좋아요' '술이 다양해요']],[['음식이 맛있어요' '특별한 메뉴가 있어요' '대화하기 좋아요' '친절해요' '...,[['음식이 맛있어요' '술이 다양해요' '특별한 메뉴가 있어요' '가성비가 좋아요...,[['음식이 맛있어요' '친절해요' '매장이 청결해요']],[['음식이 맛있어요' '기본 안주가 좋아요' '가성비가 좋아요' '인테리어가 멋져...,[['음식이 맛있어요' '인테리어가 멋져요']],[['음식이 맛있어요' '특별한 메뉴가 있어요' '화장실이 깨끗해요' '매장이 청결...,[['음식이 맛있어요' '기본 안주가 좋아요' '술이 다양해요' '특별한 메뉴가 있...,...,[['음식이 맛있어요' '가성비가 좋아요' '음악이 좋아요' '아늑해요']],[['특별한 메뉴가 있어요' '가성비가 좋아요' '음식이 맛있어요' '대화하기 좋아...,[['음식이 맛있어요' '특별한 메뉴가 있어요' '친절해요']],[['음식이 맛있어요' '술이 다양해요' '가성비가 좋아요' '친절해요']],[['음식이 맛있어요' '가성비가 좋아요' '특별한 메뉴가 있어요' '음악이 좋아요...,[['인테리어가 멋져요' '음악이 좋아요' '대화하기 좋아요' '음식이 맛있어요']],[['음식이 맛있어요' '가성비가 좋아요']],[['친절해요' '음식이 맛있어요' '인테리어가 멋져요']],[['음식이 맛있어요' '가성비가 좋아요' '메뉴 구성이 알차요' '양이 많아요' ...,[['매장이 청결해요' '특별한 메뉴가 있어요' '음식이 맛있어요' '혼술하기 좋아...
is_advert_label,0,1,1,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0
is_advert_prob,0.062462,0.992249,0.923189,0.348189,0.993168,0.027428,0.452301,0.203145,0.991027,0.992666,...,0.021204,0.025298,0.470183,0.038245,0.02107,0.020328,0.369258,0.021173,0.988197,0.02181
sentiment,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
confidence,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

:

In [ ]:
blog["post_url"].is_unique