In [2]:
import duckdb
from pathlib import Path

# 네이버 데이터 DB로 옮기기

In [ ]:
# 네이버 데이터 파일 위치
datafiles_dir = Path("G:/My Drive/Data/naver_search_results")
restaurants_path = datafiles_dir / "restaurants_table.parquet"
navermap_reviews_path = datafiles_dir / "navermap_reviews.parquet"
naverblog_reviews_path = datafiles_dir / "naverblog_reviews_store_id.parquet" # store_id 추가 버전
navermap_reviews_labelled_path = datafiles_dir / "navermap_reviews_labelled.parquet" # 라벨링을 위해 샘플링한 애들만 모아둔 파일. 완전한 라벨링은 안 된 상태 but 라벨링 된 애들만 가지고 모델 훈련 중...

In [3]:
# 새로운 DB 파일 위치 (G 드라이브, H 드라이브 등 어디에 있는 지 확인해주세요)
new_db_path = Path(r"H:\My Drive") / "reviews.db"

In [9]:
with duckdb.connect(database=new_db_path, read_only=False) as db_conn:
    q1 = f"CREATE OR REPLACE TABLE naver_restaurants AS SELECT * FROM '{restaurants_path.as_posix()}'"
    db_conn.execute(q1)
    q2 = f"CREATE OR REPLACE TABLE navermap_reviews AS SELECT * FROM '{navermap_reviews_path.as_posix()}'"
    db_conn.execute(q2)
    q3 = f"CREATE OR REPLACE TABLE naverblog_reviews AS SELECT * FROM '{naverblog_reviews_path.as_posix()}'"
    db_conn.execute(q3)
    q4 = f"CREATE OR REPLACE TABLE navermap_reviews_labelled AS SELECT * FROM '{navermap_reviews_labelled_path.as_posix()}'"
    db_conn.execute(q4)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

# DB에서 정보 보기

In [10]:
with duckdb.connect(database=new_db_path, read_only=False) as db_conn:
    # DB에 어떤 테이블 있는 지 보기
    db_conn.sql("PRAGMA show_tables_expanded;").show() 
    # 데이터프레임으로 테이블 가져오기
    restaurants = db_conn.table("restaurants").to_df() 
    display(restaurants)

┌──────────┬─────────┬───────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┐
│ database │ schema  │           name            │                                                                                                                                                                                                 column_names                                                                                                                                                                                                  │                                                                                                                  column_types                                                                                                                   │ temporary │
│ varchar  │ varchar │          varchar          │                                                                                                                                                                                                   varchar[]                                                                                                                                                                                                   │                                                                                                                    varchar[]                                                                                                                    │  boolean  │
├──────────┼─────────┼───────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┤
│ reviews  │ main    │ instagram_restaurants     │ [food_house, search, reviews, label]                                                                                                                                                                                                                                                                                                                                                                          │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR]                                                                                                                                                                                                            │ false     │
│ reviews  │ main    │ kakaomap_restaurants      │ [store_name, jibun_address, road_address, X_EPSG_5174, Y_EPSG_5174, moreview_url, kakaomap_id]                                                                                                                                                                                                                                                                                                                │ [VARCHAR, VARCHAR, VARCHAR, DOUBLE, DOUBLE, VARCHAR, VARCHAR]                                                                                                                                                                                   │ false     │
│ reviews  │ main    │ kakaomap_reviews          │ [store_name, category, kakaomap_id, reviewer_name, reviewer_level, num_reviews, avg_rating, num_followers, review_date, rating, review_text, photo_url]                                                                                                                                                                                                                                                       │ [VARCHAR, VARCHAR, BIGINT, VARCHAR, BIGINT, BIGINT, DOUBLE, BIGINT, VARCHAR, DOUBLE, VARCHAR, VARCHAR]                                                                                                                                          │ false     │
│ reviews  │ main    │ kakaomap_reviews_labelled │ [store_name, category, kakaomap_id, reviewer_name, reviewer_level, num_reviews, avg_rating, num_followers, review_date, rating, review_text, photo_url, processed_review, processed_cleaned, ad_keyword_count, predicted_label, adreview_prob, realreview_prob]                                                                                                                                               │ [VARCHAR, VARCHAR, BIGINT, VARCHAR, BIGINT, BIGINT, DOUBLE, BIGINT, VARCHAR, DOUBLE, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, BIGINT, DOUBLE, DOUBLE]                                                                                        │ false     │
│ reviews  │ main    │ naver_restaurants         │ [naver_store_id, store_name, naver_store_name, category, naver_jibun_address, naver_road_address, naver_blog_review_count, naver_place_review_count, X_naver_WGS_84, Y_naver_WGS_84, X_EPSG_5174, Y_EPSG_5174, jibun_address, road_address]                                                                                                                                                                   │ [VARCHAR, VARCHAR, VARCHAR, 'VARCHAR[]', VARCHAR, VARCHAR, BIGINT, BIGINT, VARCHAR, VARCHAR, DOUBLE, DOUBLE, VARCHAR, VARCHAR]                                                                                                                  │ false     │
│ reviews  │ main    │ naverblog_reviews         │ [post_url, editorversion, blogname, commentcount, post_title, post_date, author, text, img_url, sticker_url, vid_thumb_url, store_id]                                                                                                                                                                                                                                                                         │ [VARCHAR, VARCHAR, VARCHAR, DOUBLE, VARCHAR, TIMESTAMP, VARCHAR, VARCHAR, 'VARCHAR[]', 'VARCHAR[]', 'VARCHAR[]', VARCHAR]                                                                                                                       │ false     │
│ reviews  │ main    │ navermap_reviews          │ [review_id, store_id, store_naver_name, store_name, store_reply, review_text, num_of_media, image_links, video_thumbnail_links, visit_count, author_nickname, author_total_reviews, author_total_images, reactions_fun, reactions_helpful, reactions_wannago, reactions_cool, review_datetime, review_year, visit_keywords, purchase_item, rating, keyword_tags_code, keyword_tags_hangul, __index_level_0__] │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, 'VARCHAR[]', 'VARCHAR[]', BIGINT, VARCHAR, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, TIMESTAMP_NS, BIGINT, 'VARCHAR[]', VARCHAR, DOUBLE, 'VARCHAR[]', 'VARCHAR[]', BIGINT] │ false     │
│ reviews  │ main    │ navermap_reviews_labelled │ [review_id, store_id, store_naver_name, store_name, review_text, num_of_media, image_links, video_thumbnail_links, visit_count, author_nickname, author_total_reviews, author_total_images, reactions_fun, reactions_helpful, reactions_wannago, reactions_cool, review_datetime, review_year, visit_keywords, purchase_item, rating, keyword_tags_code, keyword_tags_hangul, is_advert]                      │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, BIGINT, 'VARCHAR[]', 'VARCHAR[]', BIGINT, VARCHAR, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, DOUBLE, TIMESTAMP_NS, DOUBLE, 'VARCHAR[]', VARCHAR, DOUBLE, 'VARCHAR[]', 'VARCHAR[]', BOOLEAN]         │ false     │
│ reviews  │ main    │ restaurants               │ [naver_store_id, store_name, naver_store_name, category, naver_jibun_address, naver_road_address, naver_blog_review_count, naver_place_review_count, X_naver_WGS_84, Y_naver_WGS_84, X_EPSG_5174, Y_EPSG_5174, jibun_address, road_address]                                                                                                                                                                   │ [VARCHAR, VARCHAR, VARCHAR, 'VARCHAR[]', VARCHAR, VARCHAR, BIGINT, BIGINT, VARCHAR, VARCHAR, DOUBLE, DOUBLE, VARCHAR, VARCHAR]                                                                                                                  │ false     │
└──────────┴─────────┴───────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┘

,naver_store_id,store_name,naver_store_name,category,naver_jibun_address,naver_road_address,naver_blog_review_count,naver_place_review_count,X_naver_WGS_84,Y_naver_WGS_84,X_EPSG_5174,Y_EPSG_5174,jibun_address,road_address
0,1006911838,Amare Tutti(아마레뚜띠),4층 아마레뚜띠,"[음식점, 카페,디저트]",서울특별시 마포구 연남동 228-21 4층,서울특별시 마포구 동교로 264 4층,39,203,126.9254135,37.5630327,193336.869916,451197.857184,서울특별시 마포구 연남동 228-21,"서울특별시 마포구 동교로 264, 4층 (연남동)"
1,1007120813,춘희,춘희,"[술집, 바(BAR)]",서울특별시 마포구 연남동 226-21 지1층,서울특별시 마포구 성미산로 193 지1층,1,1,126.9267280,37.5628981,193455.422987,451184.255870,서울특별시 마포구 연남동 226-21,"서울특별시 마포구 성미산로 193, 지1층 (연남동)"
2,1007494188,멜티스트,멜티스트,"[카페,디저트, 케이크전문]",서울특별시 마포구 연남동 568-19 1층 멜티스트,서울특별시 마포구 연남로1길 39 1층 멜티스트,26,31,126.9210670,37.5599019,192958.190594,450847.440082,서울특별시 마포구 연남동 568-19,"서울특별시 마포구 연남로1길 39, 1층 일부호 (연남동)"
3,1010873065,코리코카페(Koriko Cafe),코리코카페 연남점,"[음식점, 카페,디저트]",서울특별시 마포구 연남동 223-96 대원미디어 연남점,서울특별시 마포구 성미산로 165-7 대원미디어 연남점,1523,10062,126.9247638,37.5650670,193282.847345,451421.067423,서울특별시 마포구 연남동 223-96,"서울특별시 마포구 성미산로 165-7, 지층,1층,2층 (연남동)"
4,1013534030,연남 흑돼지,연남 흑돼지,"[한식, 돼지고기구이]",서울특별시 마포구 연남동 260-52 연남흑돼지,서울특별시 마포구 동교로32길 3 연남흑돼지,462,341,126.9245345,37.5608414,193263.533815,450953.696000,서울특별시 마포구 연남동 260-52,"서울특별시 마포구 동교로32길 3, 1층 (연남동)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,703816866,올바른김밥,올바른김밥,"[분식, 김밥]",서울특별시 마포구 연남동 227-5 1층 올바른김밥,서울특별시 마포구 동교로46길 42 1층 올바른김밥,360,2721,126.9268129,37.5621011,193462.794150,451092.249061,서울특별시 마포구 연남동 227-5 1층일부,"서울특별시 마포구 동교로46길 42, 1층일부 (연남동)"
647,750761196,장작집,장작집 연남본점,"[음식점, 한식]",서울특별시 마포구 연남동 570-38 1층 장작집,서울특별시 마포구 월드컵북로6길 19 1층 장작집,846,750,126.9196227,37.5582519,192822.946369,450675.868680,서울특별시 마포구 연남동 570-38,"서울특별시 마포구 월드컵북로6길 19, 가동 (연남동, 1층일부)"
648,778485723,작가식당,작가식당,"[한식, 닭요리]",서울특별시 마포구 연남동 561-6 1층 작가식당,서울특별시 마포구 동교로27길 74 1층 작가식당,129,231,126.9205900,37.5608999,192914.853763,450962.747590,서울특별시 마포구 연남동 561-6,"서울특별시 마포구 동교로27길 74 (연남동, 1층 일부)"
649,882437826,각별한,각별한,"[술집, 바(BAR)]",서울특별시 마포구 연남동 383-44 1층 각별한,서울특별시 마포구 동교로38길 27-14 1층 각별한,56,43,126.9262220,37.5619360,193409.791441,451079.142850,서울특별시 마포구 연남동 383-44,"서울특별시 마포구 동교로38길 27-14 (연남동, 지1층일부)"
650,934931882,봉구비어,봉구비어 연남동점,"[술집, 맥주,호프]",서울특별시 마포구 연남동 260-25,서울특별시 마포구 동교로36길 3,36,341,126.9245858,37.5613012,193266.806522,451003.543478,서울특별시 마포구 연남동 260-25번지,"서울특별시 마포구 동교로36길 3 (연남동, 2층)"

In [4]:
with duckdb.connect(database=new_db_path, read_only=True) as db_conn:
    blog = db_conn.table("naverblog_reviews").to_df() 
    display(blog)

,post_url,editorversion,blogname,commentcount,post_title,post_date,author,text,img_url,sticker_url,vid_thumb_url,store_id
0,https://m.blog.naver.com/leeginee/223758075600,4,때깔좋은 기니,0.0,연남동 카페 4층 아마레뚜띠 갔어요,2025-02-12 15:58:00,숮기니,연남동 카페 4층 아마레뚜띠 갔어요\n25.1.19\n4층 아마레뚜띠\n11:00~...,[https://mblogthumb-phinf.pstatic.net/MjAyNTAy...,[https://storep-phinf.pstatic.net/ogq_5f169472...,<NA>,1006911838
1,https://m.blog.naver.com/mjy9165/223557468102,4,밍톨이의 소소한 일상 :),20.0,[연남동] 이색 커피와 디저트가 있는 이태리 카페 아마레뚜띠,2024-08-23 00:05:00,밍톨이,아마레뚜띠🏠 서울 마포구 동교로 264 4층⏰ 11:00 - 22:00 / 화 정기...,<NA>,[https://storep-phinf.pstatic.net/ogq_5fdfe745...,[https://phinf.pstatic.net/image.nmv/blog_2024...,1006911838
2,https://m.blog.naver.com/angelife_828/22374663...,4,우당탕탕 맛집ㆍ카페ㆍ뷰티,37.0,홍대에서 🙉포스터를 보셨다면..?! 4층 아마레뚜띠 카페로 가십쇼@@,2025-02-03 22:01:00,김즐레,안녕하세요 숭이숭이 원숭이 김즐레 입니다\n오늘은 특별한 카페를 해볼까 합니다@@바...,[https://mblogthumb-phinf.pstatic.net/MjAyNTA2...,[https://storep-phinf.pstatic.net/ogq_629f0e87...,[https://phinf.pstatic.net/image.nmv/blog_2025...,1006911838
3,https://m.blog.naver.com/timeisgoldhee/2237465...,4,그미 놀로그,4.0,1월끝 세월아,2025-02-03 21:26:00,그미,\n\n1월부터 샐러드 정기배달중꽤나 만족~ \n단톡잼\n똥꾸랭끼 쉬해서 러그세탁중...,[https://mblogthumb-phinf.pstatic.net/MjAyNTAx...,<NA>,<NA>,1006911838
4,https://m.blog.naver.com/r__in__/223527190545,4,유부녀가 된 꽃신 누나,0.0,연남동카페 커피가 맛있는 이태리옥탑 아마레뚜띠,2024-07-28 09:00:00,Ram,"더운 여름날, 오랜만에 짝꿍과 데이트하던 중카페를 가자! 하고 정말 눈에 보이는 곳...",<NA>,[https://storep-phinf.pstatic.net/ogq_61b50e89...,<NA>,1006911838
...,...,...,...,...,...,...,...,...,...,...,...,...
49382,https://m.blog.naver.com/guswl8041/221025681083,3,또새의 일상,0.0,*안주가 맛있는 홍대 봉구비어 연남동점*,2017-06-09 23:20:00,김또새,위치: 서울시 마포구 마포구 동교로36길 3 봉구비어 연남동점전화: 02-333-9...,[https://mblogthumb-phinf.pstatic.net/MjAxNzA2...,[https://storep-phinf.pstatic.net/moonk_02/ori...,<NA>,934931882
49383,https://m.blog.naver.com/kangmable/221802272057,4,대형견 지나와 본깜‍이,2.0,홍대입구역 봉구비어 연남동점 더치맥주,2020-02-09 18:47:00,kangmable,안뇽하세요~~본깜입니당.가볍게 맥주 한잔할 수 있는곳 연남동 봉구비어에 왔습니당.2...,[https://mblogthumb-phinf.pstatic.net/MjAyMDAy...,[https://storep-phinf.pstatic.net/linesoft_01/...,<NA>,934931882
49384,https://m.blog.naver.com/mds1120/222075530325,4,냉혈인간 의 일상,1.0,홍대 봉구비어 하이볼,2020-08-30 21:35:00,냉혈인간,왜 이리 봉구비어 찾기가 힘드냐 ;;;;홍대 쪽 봉구비어 찾아서 갔는데 ...칵테일...,[https://mblogthumb-phinf.pstatic.net/MjAyMDA4...,<NA>,<NA>,934931882
49385,https://m.blog.naver.com/selli/222074827727,4,내가 만든 블로그,0.0,연남동 맥주 - 봉구비어,2020-08-29 23:59:00,비기닝,봉구비어 연남동점 리뷰 👀\n옛날에 봉구비어 자주 갔었는데!요즘은 잘 안보여서 안갔...,[https://mblogthumb-phinf.pstatic.net/MjAyMDA4...,<NA>,<NA>,934931882
49386,https://m.blog.naver.com/jwad7239/221727527841,2,정을 더하다,12.0,연남동 봉구비어! 유쾌한 사장님이 특징인 가게! 가맥집 가성비 맛집 솔직 후기!,2019-12-05 08:37:00,정을 더하다,안녕하세요~\n정을 더하다의 정원애드컴 입니다!\n\n오늘의 포스팅은\n친구들과 가...,[https://mblogthumb-phinf.pstatic.net/MjAxOTEw...,<NA>,<NA>,934931882

In [7]:
blog["post_url"].is_unique

True